#!/bin/bash

echo "Run Pythia8 with Pb ions"
time=$(date)
echo "Start time : $time"

seed=1000
jobid=$SLURM_JOB_ID
seed=$((seed+jobid))

./pythiaHI ${2} "${3}/output.root" $seed
time=$(date)
echo "End time : $time"
